'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { useState } from "react";
import Navbar from "./_componenet/NavBar/Navbar";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isMenuOpen, setMenuOpen] = useState(false);

  const toggleMenu = () => {
    setMenuOpen(!isMenuOpen);
  };
  return (
    <html lang="en">

      <body className={inter.className}>
      <Navbar/>

        {children}</body>
    </html>
  );
}
